In [ ]:
import numpy as np

In [ ]:
# Problem 1:
print("Problem 1: Array Creation")
empty_array = np.empty((2, 2))
print("1. Empty array (2x2):\n", empty_array)
ones_array = np.ones((4, 2))
print("\n2. All ones array (4x2):\n", ones_array)
full_array = np.full((3, 3), 7)
print("\n3. Full array (3x3) with 7:\n", full_array)
ref_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(ref_array)
print("\n4. Zeros like ref_array:\n", zeros_like_array)
ones_like_array = np.ones_like(ref_array)
print("\n5. Ones like ref_array:\n", ones_like_array)
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("\n6. Converted list to array:\n", converted_array)

Problem 1: Array Creation
1. Empty array (2x2):
 [[23. 51.]
 [13. 29.]]

2. All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array (3x3) with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like ref_array:
 [[0 0]
 [0 0]]

5. Ones like ref_array:
 [[1 1]
 [1 1]]

6. Converted list to array:
 [1 2 3 4]


In [ ]:
# Problem 2:
print("\nProblem 2: Array Manipulation")
range_array = np.arange(10, 50)
print("1. Array from 10 to 49:\n", range_array)
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix from 0 to 8:\n", matrix_3x3)
identity_matrix = np.eye(3)
print("\n3. Identity matrix (3x3):\n", identity_matrix)
random_array = np.random.random(30)
print("\n4. Random array (size 30):\n", random_array)
print("Mean of array:", random_array.mean())
rand_10x10 = np.random.random((10, 10))
print("\n5. Random 10x10 array:\n", rand_10x10)
print("Min:", rand_10x10.min(), "Max:", rand_10x10.max())
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with 5th element = 1:\n", zero_array)
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 checkerboard pattern:\n", checkerboard)


Problem 2: Array Manipulation
1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30):
 [0.16706618 0.51391568 0.63129795 0.60159322 0.35982205 0.8907916
 0.92060649 0.6981321  0.95710001 0.36257303 0.60979088 0.95407398
 0.15017943 0.60089691 0.39780383 0.95193142 0.18889946 0.80761812
 0.49830679 0.77588445 0.22413673 0.35699578 0.70306652 0.18423196
 0.56246619 0.78776215 0.42719555 0.94282907 0.78589611 0.4647441 ]
Mean of array: 0.582586924771185

5. Random 10x10 array:
 [[0.8444858  0.07496715 0.92749832 0.54203838 0.38869024 0.28473211
  0.70649358 0.71349418 0.10589333 0.2290473 ]
 [0.45245374 0.15236727 0.1364742  0.89721691 0.77954977 0.20476386
  0.61255058 0.50249168 0.56400069 0.63058875]
 [0.91535714 0.79207607 0.39067805 0.49732774 0

In [ ]:
# Problem 3:
print("\nProblem 3: Array Operations")
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
print("x:\n", x)
print("y:\n", y)
print("v:", v)
print("w:", w)
print("\n1. x + y:\n", x + y)
print("2. x - y:\n", x - y)
print("3. x * 3:\n", x * 3)
print("4. Square of x:\n", x ** 2)
print("\n5. Dot products:")
print("v . w =", np.dot(v, w))
print("x . v =\n", np.dot(x, v))
print("x . y =\n", np.dot(x, y))
print("\n6. Concatenate x and y along rows:\n", np.concatenate((x, y), axis=0))
print("Concatenate v and w along columns:\n", np.vstack((v, w)))
print("\n7. Concatenate x and v:")
try:
    result = np.concatenate((x, v), axis=0)
    print(result)
except ValueError as e:
    print("Error:", e)


Problem 3: Array Operations
x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]

1. x + y:
 [[ 6  8]
 [10 13]]
2. x - y:
 [[-4 -4]
 [-4 -3]]
3. x * 3:
 [[ 3  6]
 [ 9 15]]
4. Square of x:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
v . w = 219
x . v =
 [29 77]
x . y =
 [[19 22]
 [50 58]]

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

7. Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
# Problem 4:
print("\nProblem 4: Matrix Operations")
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A * A_inv:\n", identity_check)
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.allclose(AB, BA))
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("(AB)^T == B^T * A^T?", np.allclose(AB_T, BT_AT))


Problem 4: Matrix Operations
1. A * A_inv:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False

3. (AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T? True


In [ ]:
print("\nSolving Linear Equations")
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_sys = np.array([-1, -3, 9])
A_inv_sys = np.linalg.inv(A_sys)
X = np.dot(A_inv_sys, B_sys)
print("Solution [x, y, z]:", X)


Solving Linear Equations
Solution [x, y, z]: [ 2.  1. -2.]


In [ ]:
import time
size = 1_000_000
matrix_size = 1000
print("Experiment: How Fast is NumPy?\n")


Experiment: How Fast is NumPy?



In [ ]:
# 1. Element-wise Addition
print("1. Element-wise Addition")
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds\n")

1. Element-wise Addition
Python List Addition Time: 0.08253169059753418 seconds
NumPy Array Addition Time: 0.0009999275207519531 seconds



In [ ]:
# 2. Element-wise Multiplication
print("2. Element-wise Multiplication")
start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")
start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds\n")

2. Element-wise Multiplication
Python List Multiplication Time: 0.10497736930847168 seconds
NumPy Array Multiplication Time: 0.0020051002502441406 seconds



In [ ]:
# 3. Dot Product
print("3. Dot Product")
start = time.time()
list_dot = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")
start = time.time()
np_dot = np.dot(arr1, arr2)
end = time.time()
print("NumPy Array Dot Product Time:", end - start, "seconds\n")

3. Dot Product
Python List Dot Product Time: 0.2013871669769287 seconds
NumPy Array Dot Product Time: 0.0009996891021728516 seconds



In [ ]:
# 4. Matrix Multiplication
print("4. Matrix Multiplication")
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
start = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")

np_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
np_result_matrix = np.dot(np_matrix1, np_matrix2)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start, "seconds")
